'use strict';function t(e,a,b,c){e.v.kc(e.Xa,a,b,c,void 0)}function B(e,a,b,c){e.v.qa?t(e,a,b,c):e.v.df()._OnMessageFromDOM({type:"event",component:e.Xa,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function D(e,a,b){e.v.B(e.Xa,a,b)}function E(e,a){for(const [b,c]of a)D(e,b,c)}function F(e){e.Nb||(e.v.Pe(e.Zd),e.Nb=!0)}window.Ba=class{constructor(e,a){this.v=e;this.Xa=a;this.Nb=!1;this.Zd=()=>this.Ea()}bd(){}Ea(){}};function G(e){-1!==e.Pa&&(self.clearTimeout(e.Pa),e.Pa=-1)}
window.Ge=class{constructor(e,a){this.Jc=e;this.rg=a;this.Pa=-1;this.Ob=-Infinity;this.$d=()=>{this.Pa=-1;this.Ob=Date.now();this.bb=!0;this.Jc();this.bb=!1};this.Jd=this.bb=!1}c(){G(this);this.$d=this.Jc=null}};"use strict";function H(e,a){const b=a.elementId,c=e.bc(b,a);e.Y.set(b,c);a.isVisible||(c.style.display="none");a=e.tc(c);a.addEventListener("focus",()=>{I(e,"elem-focused",b)});a.addEventListener("blur",()=>{I(e,"elem-blurred",b)});e.Ib&&document.body.appendChild(c)}
function K(e,a,b){D(e,a,c=>{const f=e.Y.get(c.elementId);return b(f,c)})}function I(e,a,b,c){c||(c={});c.elementId=b;t(e,a,c)}function L(e,a,b,c){c||(c={});c.elementId=b;B(e,a,c)}
window.fd=class extends self.Ba{constructor(e,a){super(e,a);this.Y=new Map;this.Ib=!0;E(this,[["create",b=>H(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Ib&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Ib&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Ib){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.Ua(c,b)}}],["focus",b=>this.Ec(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);K(this,"get-element",b=>b)}bc(){throw Error("required override");}Ua(){throw Error("required override");}tc(e){return e}Ec(e){const a=this.tc(this.Y.get(e.elementId));
e.focus?a.focus():a.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(v){if(v.Bg){const h=document.createElement("script");h.async=!1;h.textContent=v.Eg;document.head.appendChild(h)}else return new Promise((h,k)=>{const d=document.createElement("script");d.onload=h;d.onerror=k;d.async=!1;d.src=v;document.head.appendChild(d)})}let b=new Audio;const c={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),
"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;async function f(v){v=await n(v);return(new TextDecoder("utf-8")).decode(v)}function n(v){return new Promise((h,k)=>{const d=new FileReader;d.onload=g=>h(g.target.result);d.onerror=g=>k(g);d.readAsArrayBuffer(v)})}const q=[];let u=0;window.RealFile=window.File;const x=[],A=new Map,w=new Map;let y=0;const C=[];self.Qg=function(v){if("function"!==
typeof v)throw Error("runOnStartup called without a function");C.push(v)};const z=new Set(["cordova","playable-ad","instant-games"]);window.ka=class v{constructor(h){this.qa=h.Gg;this.oa=null;this.K="";this.Wb=h.Dg;this.qb={};this.na=this.Ia=this.pb=null;this.Lb=[];this.eb=this.J=this.Na=null;this.Ma=-1;this.wg=()=>this.Cf();this.La=[];this.C=h.ae;!this.qa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.qa=!1);z.has(this.C)&&this.qa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.qa=!1);this.Qb=this.ha=null;"html5"!==this.C&&"playable-ad"!==this.C||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.lf(k));this.B("runtime","create-job-worker",()=>this.mf());"cordova"===this.C?document.addEventListener("deviceready",()=>this.wd(h)):this.wd(h)}c(){this.qc();this.oa&&(this.oa=
this.oa.onmessage=null);this.pb&&(this.pb.terminate(),this.pb=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.J&&(this.J.parentElement.removeChild(this.J),this.J=null)}kd(){return e&&"cordova"===this.C}ub(){return e&&z.has(this.C)||navigator.standalone}async wd(h){"preview"===this.C&&(this.na=document.createElement("div"),this.na.className="previewLoadingMessage",this.na.textContent=h.Og,document.body.appendChild(this.na));if("playable-ad"===this.C){this.ha=self.c3_base64files;this.Qb={};await this.Ue();
for(let d=0,g=h.Qa.length;d<g;++d){var k=h.Qa[d].toLowerCase();this.Qb.hasOwnProperty(k)?h.Qa[d]={Bg:!0,Eg:this.Qb[k]}:this.ha.hasOwnProperty(k)&&(h.Qa[d]=URL.createObjectURL(this.ha[k]))}}h.yg?this.K=h.yg:(k=location.origin,this.K=("null"===k?"file:///":k)+location.pathname,k=this.K.lastIndexOf("/"),-1!==k&&(this.K=this.K.substr(0,k+1)));if(h.Ig)for(const [d,g]of Object.entries(h.Ig))this.qb[d]=URL.createObjectURL(g);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=d=>this._OnMessageFromRuntime(d.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.yf(d));this.eb=new self.Ce(this);await M(this.eb);this.ld();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.qa?await this.ff(h,k.port2):await this.ef(h,k.port2)}uc(h){return this.qb.hasOwnProperty(h)?this.qb[h]:h.endsWith("/workermain.js")&&this.qb.hasOwnProperty("workermain.js")?this.qb["workermain.js"]:"playable-ad"===this.C&&
this.ha.hasOwnProperty(h.toLowerCase())?URL.createObjectURL(this.ha[h.toLowerCase()]):h}async cc(h,k,d){if(h.startsWith("blob:"))return new Worker(h,d);if(this.kd()&&"file:"===location.protocol)return h=await this.ac(this.Wb+h),new Worker(URL.createObjectURL(new Blob([h],{type:"application/javascript"})),d);h=new URL(h,k);if(location.origin!==h.origin){h=await fetch(h);if(!h.ok)throw Error("failed to fetch worker script");h=await h.blob();return new Worker(URL.createObjectURL(h),d)}return new Worker(h,
d)}wa(){return Math.max(window.innerWidth,1)}va(){return Math.max(window.innerHeight,1)}ld(){if(this.ub()){const h=document.documentElement.style,k=document.body.style,d=window.innerWidth<window.innerHeight,g=d?window.screen.width:window.screen.height;k.height=h.height=(d?window.screen.height:window.screen.width)+"px";k.width=h.width=g+"px"}}ud(h){var k=this.eb;return{baseUrl:this.K,windowInnerWidth:this.wa(),windowInnerHeight:this.va(),devicePixelRatio:window.devicePixelRatio,isFullscreen:v.jc(),
projectData:h.Pg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:h.ae,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ng,jobScheduler:{inputPort:k.Pc,outputPort:k.Wc,maxNumWorkers:k.tg},supportedAudioFormats:c,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Wb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Wb+"opus.wasm.wasm",isiOSCordova:this.kd(),isiOSWebView:this.ub(),isFBInstantAvailable:"undefined"!==
typeof self.FBInstant}}async ff(h,k){var d=this.uc(h.Hg);this.pb=await this.cc(d,this.K,{name:"Runtime"});this.J=document.createElement("canvas");this.J.style.display="none";d=this.J.transferControlToOffscreen();document.body.appendChild(this.J);window.c3canvas=this.J;this.pb.postMessage(Object.assign(this.ud(h),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:d,workerDependencyScripts:h.ad||[],engineScripts:h.Qa,projectScripts:window.Mg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,d,...N(this.eb)]);this.Lb=x.map(g=>new g(this));this.td();self.c3_callFunction=(g,l)=>this.Na.gf(g,l);"preview"===this.C&&(self.goToLastErrorScript=()=>this.kc("runtime","go-to-last-error-script"))}async ef(h,k){this.J=document.createElement("canvas");this.J.style.display="none";document.body.appendChild(this.J);window.c3canvas=this.J;this.Lb=x.map(g=>new g(this));this.td();const d=h.Qa.map(g=>"string"===typeof g?(new URL(g,this.K)).toString():g);Array.isArray(h.ad)&&d.unshift(...h.ad);await Promise.all(d.map(g=>
a(g)));if(h.be&&0<h.be.length){const g=self.C3_ProjectScriptsStatus;try{if(await Promise.all(h.be.map(l=>a(l[1]))),Object.values(g).some(l=>!l)){self.setTimeout(()=>this.Ed(g),100);return}}catch(l){console.error("[Preview] Error loading project scripts: ",l);self.setTimeout(()=>this.Ed(g),100);return}}"preview"===this.C&&"object"!==typeof self.Jg.Kg?(this.Eb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(h=Object.assign(this.ud(h),{isInWorker:!1,messagePort:k,canvas:this.J,runOnStartupFunctions:C}),this.yd(),this.Ia=self.C3_CreateRuntime(h),await self.C3_InitRuntime(this.Ia,h))}Ed(h){this.Eb();h=`Failed to load project script '${Object.entries(h).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+h);alert(h)}yd(){this.Eb()}Eb(){this.na&&(this.na.parentElement.removeChild(this.na),this.na=null)}async mf(){const h=await O(this.eb);return{outputPort:h,
transferables:[h]}}df(){if(this.qa)throw Error("not available in worker mode");return this.Ia}kc(h,k,d,g,l){this.oa.postMessage({type:"event",component:h,handler:k,dispatchOpts:g||null,data:d,responseId:null},l)}md(h,k,d,g,l){const m=y++,p=new Promise((r,J)=>{w.set(m,{resolve:r,reject:J})});this.oa.postMessage({type:"event",component:h,handler:k,dispatchOpts:g||null,data:d,responseId:m},l);return p}["_OnMessageFromRuntime"](h){const k=h.type;if("event"===k)return this.sf(h);if("result"===k)this.Ff(h);
else if("runtime-ready"===k)this.Gf();else if("alert-error"===k)this.Eb(),alert(h.message);else if("creating-runtime"===k)this.yd();else throw Error(`unknown message '${k}'`);}sf(h){const k=h.component,d=h.handler,g=h.data,l=h.responseId;if(h=A.get(k))if(h=h.get(d)){var m=null;try{m=h(g)}catch(p){console.error(`Exception in '${k}' handler '${d}':`,p);null!==l&&this.Cb(l,!1,""+p);return}if(null===l)return m;m&&m.then?m.then(p=>this.Cb(l,!0,p)).catch(p=>{console.error(`Rejection from '${k}' handler '${d}':`,
p);this.Cb(l,!1,""+p)}):this.Cb(l,!0,m)}else console.warn(`[DOM] No handler '${d}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Cb(h,k,d){let g;d&&d.transferables&&(g=d.transferables);this.oa.postMessage({type:"result",responseId:h,isOk:k,result:d},g)}Ff(h){const k=h.responseId,d=h.isOk;h=h.result;const g=w.get(k);d?g.resolve(h):g.reject(h);w.delete(k)}B(h,k,d){let g=A.get(h);g||(g=new Map,A.set(h,g));if(g.has(k))throw Error(`[DOM] Component '${h}' already has handler '${k}'`);
g.set(k,d)}static ra(h){if(x.includes(h))throw Error("DOM handler already added");x.push(h)}td(){for(const h of this.Lb)if("runtime"===h.Xa){this.Na=h;return}throw Error("cannot find runtime DOM handler");}yf(h){this.kc("debugger","message",h)}Gf(){for(const h of this.Lb)h.bd()}static jc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Pe(h){this.La.push(h);this.Hc()}Sf(h){h=this.La.indexOf(h);if(-1===h)throw Error("invalid callback");this.La.splice(h,
1);this.La.length||this.qc()}Hc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.wg))}qc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Cf(){this.Ma=-1;for(const h of this.La)h();this.Hc()}ua(h){this.Na.ua(h)}Da(h){this.Na.Da(h)}Gc(){this.Na.Gc()}xb(h){this.Na.xb(h)}Ae(){return!!c["audio/webm; codecs=opus"]}async pg(h){h=await this.md("runtime","opus-decode",{arrayBuffer:h},null,[h]);return new Float32Array(h)}ze(h){return/^(?:[a-z]+:)?\/\//.test(h)||"data:"===h.substr(0,
5)||"blob:"===h.substr(0,5)}Be(h){return!this.ze(h)}async lf(h){const k=h.filename;switch(h.as){case "text":return await this.se(k);case "buffer":return await this.ac(k);default:throw Error("unsupported type");}}ed(h){const k=window.cordova.file.applicationDirectory+"www/"+h.toLowerCase();return new Promise((d,g)=>{window.resolveLocalFileSystemURL(k,l=>{l.file(d,g)},g)})}async se(h){h=await this.ed(h);return await f(h)}rc(){if(q.length&&!(8<=u)){u++;var h=q.shift();this.Ve(h.filename,h.Fg,h.Ag)}}ac(h){return new Promise((k,
d)=>{q.push({filename:h,Fg:g=>{u--;this.rc();k(g)},Ag:g=>{u--;this.rc();d(g)}});this.rc()})}async Ve(h,k,d){try{const g=await this.ed(h),l=await n(g);k(l)}catch(g){d(g)}}async Ue(){const h=[];for(const [k,d]of Object.entries(this.ha))h.push(this.Te(k,d));await Promise.all(h)}async Te(h,k){if("object"===typeof k)this.ha[h]=new Blob([k.str],{type:k.type}),this.Qb[h]=k.str;else{let d=await this.bf(k);d||(d=this.Xe(k));this.ha[h]=d}}async bf(h){try{return await (await fetch(h)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}Xe(h){h=this.Mf(h);return this.Se(h.data,h.Cg)}Mf(h){var k=h.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var d=h.substring(k+1);k=h.substring(5,k).split(";");h=k[0]||"";const g=k[2];d="base64"===k[1]||"base64"===g?atob(d):decodeURIComponent(d);return{Cg:h,data:d}}Se(h,k){var d=h.length;let g=d>>2,l=new Uint8Array(d),m=new Uint32Array(l.buffer,0,g),p,r;for(r=p=0;p<g;++p)m[p]=h.charCodeAt(r++)|h.charCodeAt(r++)<<8|h.charCodeAt(r++)<<16|h.charCodeAt(r++)<<24;for(d&=
3;d--;)l[r]=h.charCodeAt(r),++r;return new Blob([l],{type:k})}}}"use strict";
{const e=self.ka;function a(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(d){return new Promise((g,l)=>{const m=document.createElement("link");m.onload=()=>g(m);m.onerror=p=>l(p);m.rel=
"stylesheet";m.href=d;document.head.appendChild(m)})}function u(d){return new Promise((g,l)=>{const m=new Image;m.onload=()=>g(m);m.onerror=p=>l(p);m.src=d})}async function x(d){d=URL.createObjectURL(d);try{return await u(d)}finally{URL.revokeObjectURL(d)}}function A(d){return new Promise((g,l)=>{let m=new FileReader;m.onload=p=>g(p.target.result);m.onerror=p=>l(p);m.readAsText(d)})}async function w(d,g,l){if(!/firefox/i.test(navigator.userAgent))return await x(d);var m=await A(d);m=(new DOMParser).parseFromString(m,
"image/svg+xml");const p=m.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const r=p.getAttribute("width"),J=p.getAttribute("height");if(!r.includes("%")&&!J.includes("%"))return await x(d)}p.setAttribute("width",g+"px");p.setAttribute("height",l+"px");m=(new XMLSerializer).serializeToString(m);d=new Blob([m],{type:"image/svg+xml"});return await x(d)}function y(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;d=d.parentNode}while(d);return!1}const C=new Set(["canvas",
"body","html"]);function z(d){C.has(d.target.tagName.toLowerCase())&&d.preventDefault()}function v(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()}self.C3_GetSvgImageSize=async function(d){d=await x(d);if(0<d.width&&0<d.height)return[d.width,d.height];{d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const g=d.getBoundingClientRect();document.body.removeChild(d);return[g.width,g.height]}};self.C3_RasterSvgImageBlob=async function(d,
g,l,m,p){d=await w(d,g,l);const r=document.createElement("canvas");r.width=m;r.height=p;r.getContext("2d").drawImage(d,0,0,g,l);return r};let h=!1;document.addEventListener("pause",()=>h=!0);document.addEventListener("resume",()=>h=!1);function k(){try{return window.parent&&window.parent.document.hasFocus()}catch(d){return!1}}e.ra(class extends self.Ba{constructor(d){super(d,"runtime");this.Od=!0;this.Oa=-1;this.Yc="any";this.Fd=this.Gd=!1;this.Sc=this.mb=this.ya=null;d.B("canvas","update-size",m=>
this.Kf(m));d.B("runtime","invoke-download",m=>this.wf(m));d.B("runtime","raster-svg-image",m=>this.Df(m));d.B("runtime","get-svg-image-size",m=>this.uf(m));d.B("runtime","set-target-orientation",m=>this.If(m));d.B("runtime","register-sw",()=>this.Ef());d.B("runtime","post-to-debugger",m=>this.Ad(m));d.B("runtime","go-to-script",m=>this.Ad(m));d.B("runtime","before-start-ticking",()=>this.kf());d.B("runtime","debug-highlight",m=>this.nf(m));d.B("runtime","enable-device-orientation",()=>this.Re());
d.B("runtime","enable-device-motion",()=>this.Qe());d.B("runtime","add-stylesheet",m=>this.jf(m));d.B("runtime","alert",m=>this.yc(m));d.B("runtime","hide-cordova-splash",()=>this.vf());const g=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const p=m.target;g.has(p.tagName.toLowerCase())||y(p)||m.preventDefault()});const l=d.J;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",z);l.addEventListener("selectstart",z);l.addEventListener("gesturehold",
z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),l.addEventListener("pointerdown",z)):l.addEventListener("touchstart",z);this.jb=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",v,{passive:!1});window.addEventListener("wheel",v,{passive:!1});window.addEventListener("resize",()=>this.Lf());d.ub()&&window.addEventListener("focusout",()=>{{const r=
document.activeElement;if(r){var m=r.tagName.toLowerCase();var p=new Set("email number password search tel text url".split(" "));m="textarea"===m?!0:"input"===m?p.has(r.type.toLowerCase()||"text"):y(r)}else m=!1}m||(document.scrollingElement.scrollTop=0)});this.Ja=new Set;this.Rb=new WeakSet;this.ma=!1}kf(){"cordova"===this.v.C?(document.addEventListener("pause",()=>this.Fc(!0)),document.addEventListener("resume",()=>this.Fc(!1))):document.addEventListener("visibilitychange",()=>this.Fc(document.hidden));
return{isSuspended:!(!document.hidden&&!h)}}bd(){window.addEventListener("focus",()=>this.Db("window-focus"));window.addEventListener("blur",()=>{this.Db("window-blur",{parentHasFocus:k()});this.jb=0});window.addEventListener("fullscreenchange",()=>this.Ac());window.addEventListener("webkitfullscreenchange",()=>this.Ac());window.addEventListener("mozfullscreenchange",()=>this.Ac());window.addEventListener("fullscreenerror",g=>this.Bc(g));window.addEventListener("webkitfullscreenerror",g=>this.Bc(g));
window.addEventListener("mozfullscreenerror",g=>this.Bc(g));window.addEventListener("keydown",g=>this.zd("keydown",g));window.addEventListener("keyup",g=>this.zd("keyup",g));window.addEventListener("dblclick",g=>this.Cc("dblclick",g,c));window.addEventListener("wheel",g=>this.Af(g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",g=>{this.vc(g);this.Va("pointerdown",g)}),this.v.qa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.mb=new self.Ge(()=>this.$e(),
5),this.mb.Jd=!0,window.addEventListener("pointerrawupdate",g=>this.Bf(g))):window.addEventListener("pointermove",g=>this.Va("pointermove",g)),window.addEventListener("pointerup",g=>this.Va("pointerup",g)),window.addEventListener("pointercancel",g=>this.Va("pointercancel",g))):(window.addEventListener("mousedown",g=>{this.vc(g);this.Dc("pointerdown",g)}),window.addEventListener("mousemove",g=>this.Dc("pointermove",g)),window.addEventListener("mouseup",g=>this.Dc("pointerup",g)),window.addEventListener("touchstart",
g=>{this.vc(g);this.Bb("pointerdown",g)}),window.addEventListener("touchmove",g=>this.Bb("pointermove",g)),window.addEventListener("touchend",g=>this.Bb("pointerup",g)),window.addEventListener("touchcancel",g=>this.Bb("pointercancel",g)));const d=()=>this.Gc();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("gamepadconnected",d,!0)}Db(d,g){t(this,d,g||null,n)}wa(){return this.v.wa()}va(){return this.v.va()}Lf(){const d=
this.wa(),g=this.va();this.Db("window-resize",{innerWidth:d,innerHeight:g,devicePixelRatio:window.devicePixelRatio});this.v.ub()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Bd(d,g,0))}Tf(d,g,l){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Bd(d,g,l),48)}Bd(d,g,l){const m=this.wa(),p=this.va();this.Oa=-1;m!=d||p!=g?this.Db("window-resize",{innerWidth:m,innerHeight:p,devicePixelRatio:window.devicePixelRatio}):10>l&&this.Tf(m,p,l+1)}If(d){this.Yc=d.targetOrientation}lg(){const d=this.Yc;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(d):screen.webkitLockOrientation?g=screen.webkitLockOrientation(d):screen.mozLockOrientation?g=screen.mozLockOrientation(d):screen.msLockOrientation&&(g=screen.msLockOrientation(d));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",
g)}}Ac(){const d=e.jc();d&&"any"!==this.Yc&&this.lg();t(this,"fullscreenchange",{isFullscreen:d,innerWidth:this.wa(),innerHeight:this.va()})}Bc(d){console.warn("[Construct 3] Fullscreen request failed: ",d);t(this,"fullscreenerror",{isFullscreen:e.jc(),innerWidth:this.wa(),innerHeight:this.va()})}Fc(d){d?this.v.qc():this.v.Hc();t(this,"visibilitychange",{hidden:d})}zd(d,g){"Backspace"===g.key&&z(g);const l=b.get(g.code)||g.code;B(this,d,{code:l,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,
ctrlKey:g.ctrlKey,metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},c)}Af(d){t(this,"wheel",{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},c)}Cc(d,g,l){a(g)||B(this,d,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,timeStamp:g.timeStamp},l)}Dc(d,g){if(!a(g)){var l=this.jb;"pointerdown"===d&&0!==l?d="pointermove":"pointerup"===
d&&0!==g.buttons&&(d="pointermove");B(this,d,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:l,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},c);this.jb=g.buttons;this.Cc(g.type,g,f)}}Va(d,g){if(this.mb&&"pointermove"!==d){var l=this.mb;l.bb||(G(l),l.Ob=Date.now())}l=0;"mouse"===g.pointerType&&(l=this.jb);B(this,d,{pointerId:g.pointerId,pointerType:g.pointerType,
button:g.button,buttons:g.buttons,lastButtons:l,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},c);"mouse"===g.pointerType&&(l="mousemove","pointerdown"===d?l="mousedown":"pointerup"===d&&(l="pointerup"),this.Cc(l,g,f),this.jb=g.buttons)}Bf(d){this.Sc=d;d=this.mb;if(-1===d.Pa){var g=Date.now(),l=g-d.Ob,m=d.rg;
l>=m&&d.Jd?(d.Ob=g,d.bb=!0,d.Jc(),d.bb=!1):d.Pa=self.setTimeout(d.$d,Math.max(m-l,4))}}$e(){this.Va("pointermove",this.Sc);this.Sc=null}Bb(d,g){for(let l=0,m=g.changedTouches.length;l<m;++l){const p=g.changedTouches[l];B(this,d,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,width:2*(p.radiusX||p.webkitRadiusX||0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:g.timeStamp},c)}}vc(d){window!==window.top&&window.focus();this.xd(d.target)&&document.activeElement&&!this.xd(document.activeElement)&&document.activeElement.blur()}xd(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}Re(){this.Gd||(this.Gd=!0,window.addEventListener("deviceorientation",d=>this.qf(d)),window.addEventListener("deviceorientationabsolute",d=>this.rf(d)))}Qe(){this.Fd||(this.Fd=!0,window.addEventListener("devicemotion",
d=>this.pf(d)))}qf(d){t(this,"deviceorientation",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp,webkitCompassHeading:d.webkitCompassHeading,webkitCompassAccuracy:d.webkitCompassAccuracy},c)}rf(d){t(this,"deviceorientationabsolute",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp},c)}pf(d){let g=null;var l=d.acceleration;l&&(g={x:l.x||0,y:l.y||0,z:l.z||0});l=null;var m=d.accelerationIncludingGravity;m&&(l={x:m.x||
0,y:m.y||0,z:m.z||0});m=null;const p=d.rotationRate;p&&(m={alpha:p.alpha||0,beta:p.beta||0,gamma:p.gamma||0});t(this,"devicemotion",{acceleration:g,accelerationIncludingGravity:l,rotationRate:m,interval:d.interval,timeStamp:d.timeStamp},c)}Kf(d){const g=this.v,l=g.J;l.style.width=d.styleWidth+"px";l.style.height=d.styleHeight+"px";l.style.marginLeft=d.marginLeft+"px";l.style.marginTop=d.marginTop+"px";g.ld();this.Od&&(l.style.display="",this.Od=!1)}wf(d){const g=d.url;d=d.filename;const l=document.createElement("a"),
m=document.body;l.textContent=d;l.href=g;l.download=d;m.appendChild(l);l.click();m.removeChild(l)}async Df(d){var g=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);g=g?await createImageBitmap(d,g):await createImageBitmap(d);return{imageBitmap:g,transferables:[g]}}async uf(d){return await self.C3_GetSvgImageSize(d.blob)}async jf(d){await q(d.url)}Gc(){var d=[...this.Ja];this.Ja.clear();if(!this.ma)for(const g of d)(d=g.play())&&
d.catch(()=>{this.Rb.has(g)||this.Ja.add(g)})}ua(d){if("function"!==typeof d.play)throw Error("missing play function");this.Rb.delete(d);let g;try{g=d.play()}catch(l){this.Ja.add(d);return}g&&g.catch(()=>{this.Rb.has(d)||this.Ja.add(d)})}Da(d){this.Ja.delete(d);this.Rb.add(d)}xb(d){this.ma=!!d}vf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}nf(d){if(d.show){this.ya||(this.ya=document.createElement("div"),this.ya.id="inspectOutline",document.body.appendChild(this.ya));
var g=this.ya;g.style.display="";g.style.left=d.left-1+"px";g.style.top=d.top-1+"px";g.style.width=d.width+2+"px";g.style.height=d.height+2+"px";g.textContent=d.name}else this.ya&&(this.ya.style.display="none")}Ef(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ad(d){window.c3_postToMessagePort&&(d.from="runtime",window.c3_postToMessagePort(d))}gf(d,g){return this.v.md(this.Xa,"js-invoke-function",{name:d,params:g},void 0,void 0)}yc(d){alert(d.message)}})}"use strict";
async function M(e){if(e.qg)throw Error("already initialised");e.qg=!0;var a=e.Vb.uc("dispatchworker.js");e.Lc=await e.Vb.cc(a,e.K,{name:"DispatchWorker"});a=new MessageChannel;e.Pc=a.port1;e.Lc.postMessage({type:"_init","in-port":a.port2},[a.port2]);e.Wc=await O(e)}function N(e){return[e.Pc,e.Wc]}
async function O(e){const a=e.Pd.length;var b=e.Vb.uc("jobworker.js");b=await e.Vb.cc(b,e.K,{name:"JobWorker"+a});const c=new MessageChannel,f=new MessageChannel;e.Lc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":f.port2},[c.port2,f.port2]);e.Pd.push(b);return f.port1}
self.Ce=class{constructor(e){this.Vb=e;this.K=e.K;this.K="preview"===e.C?this.K+"c3/workers/":this.K+e.Wb;this.tg=Math.min(navigator.hardwareConcurrency||2,16);this.Lc=null;this.Pd=[];this.Wc=this.Pc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ka({Gg:!0,Hg:"workermain.js",Qa:["scripts/c3runtime.js"],Dg:"scripts/",ad:[],ae:"html5"}));"use strict";
{function e(a){a.stopPropagation()}self.ka.ra(class extends self.fd{constructor(a){super(a,"button")}bc(a,b){const c=document.createElement("input");var f=c;b.isCheckbox?(c.type="checkbox",f=document.createElement("label"),f.appendChild(c),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):c.type="button";f.style.position="absolute";f.addEventListener("touchstart",
e);f.addEventListener("touchmove",e);f.addEventListener("touchend",e);f.addEventListener("mousedown",e);f.addEventListener("mouseup",e);f.addEventListener("keydown",e);f.addEventListener("keyup",e);c.addEventListener("click",()=>L(this,"click",a,{isChecked:c.checked}));b.id&&(c.id=b.id);this.Ua(f,b);return f}vd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}tc(a){return this.vd(a)}Ua(a,b){const c=this.vd(a);c.checked=b.isChecked;c.disabled=!b.isEnabled;a.title=b.title;a===c?c.value=b.text:
a.lastChild.textContent=b.text}})}"use strict";
{function e(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.ka.ra(class extends self.fd{constructor(b){super(b,"text-input");K(this,"scroll-to-bottom",c=>this.Hf(c))}bc(b,c){let f;const n=c.type;"textarea"===n?(f=document.createElement("textarea"),f.style.resize="none"):(f=document.createElement("input"),f.type=n);f.style.position="absolute";f.autocomplete="off";f.addEventListener("touchstart",e);f.addEventListener("touchmove",e);f.addEventListener("touchend",
e);f.addEventListener("mousedown",e);f.addEventListener("mouseup",e);f.addEventListener("keydown",a);f.addEventListener("keyup",a);f.addEventListener("click",q=>{q.stopPropagation();L(this,"click",b)});f.addEventListener("dblclick",q=>{q.stopPropagation();L(this,"dblclick",b)});f.addEventListener("input",()=>I(this,"change",b,{text:f.value}));c.id&&(f.id=c.id);this.Ua(f,c);return f}Ua(b,c){b.value=c.text;b.placeholder=c.placeholder;b.title=c.title;b.disabled=!c.isEnabled;b.readOnly=c.isReadOnly;b.spellcheck=
c.spellCheck;c=c.maxLength;0>c?b.removeAttribute("maxlength"):b.setAttribute("maxlength",c)}Hf(b){b.scrollTop=b.scrollHeight}})}"use strict";
{const e=180/Math.PI;self.da=class extends self.Ba{constructor(a){super(a,"audio");this.Kb=this.f=null;this.Mb=this.Oc=!1;this.pa=()=>this.mg();this.ba=[];this.D=[];this.ga=null;this.Qd="";this.Rd=-1;this.lb=new Map;this.Tc=1;this.ma=!1;this.Zc=0;this.Yb=1;this.Mc=0;this.Td="HRTF";this.Kd="inverse";this.Ud=600;this.Sd=1E4;this.Wd=1;this.Md=this.Xc=!1;this.xg=this.v.Ae();this.ca=new Map;this.Ga=new Set;this.Qc=!1;this.Uc="";this.za=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.zf(b,c);this.Jb=null;
self.C3Audio_GetOutputStream=()=>this.tf();self.C3Audio_DOMInterface=this;E(this,[["create-audio-context",b=>this.We(b)],["play",b=>this.Nf(b)],["stop",b=>this.jg(b)],["stop-all",()=>this.kg()],["set-paused",b=>this.cg(b)],["set-volume",b=>this.hg(b)],["fade-volume",b=>this.af(b)],["set-master-volume",b=>this.ag(b)],["set-muted",b=>this.bg(b)],["set-silent",b=>this.eg(b)],["set-looping",b=>this.$f(b)],["set-playback-rate",b=>this.dg(b)],["seek",b=>this.Uf(b)],["preload",b=>this.Of(b)],["unload",b=>
this.ng(b)],["unload-all",()=>this.og()],["set-suspended",b=>this.fg(b)],["add-effect",b=>this.rd(b)],["set-effect-param",b=>this.Xf(b)],["remove-effects",b=>this.Qf(b)],["tick",b=>this.Jf(b)],["load-state",b=>this.xf(b)]])}async We(a){a.isiOSCordova&&(this.Xc=!0);this.Zc=a.timeScaleMode;this.Td=["equalpower","HRTF","soundfield"][a.panningModel];this.Kd=["linear","inverse","exponential"][a.distanceModel];this.Ud=a.refDistance;this.Sd=a.maxDistance;this.Wd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.sd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.sd()};this.Kb=this.f.createGain();this.Kb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.dc();try{await Promise.all(a.preloadList.map(c=>
this.zb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}sd(){this.Mb||(this.Oc=!1,window.addEventListener("pointerup",this.pa,!0),window.addEventListener("touchend",this.pa,!0),window.addEventListener("click",this.pa,!0),window.addEventListener("keydown",this.pa,!0),this.Mb=!0)}Ye(){this.Mb&&(this.Oc=!0,window.removeEventListener("pointerup",this.pa,!0),window.removeEventListener("touchend",this.pa,!0),window.removeEventListener("click",
this.pa,!0),window.removeEventListener("keydown",this.pa,!0),this.Mb=!1)}mg(){if(!this.Oc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.Ye()}}W(){return this.f}dc(){return this.f.currentTime}sa(){return this.Kb}hd(a){return(a=this.ca.get(a.toLowerCase()))?a[0].P():this.sa()}ce(a,b){a=a.toLowerCase();let c=this.ca.get(a);c||(c=[],this.ca.set(a,c));b.Zf(c.length);
b.gg(a);c.push(b);this.Dd(a)}Dd(a){let b=this.sa();const c=this.ca.get(a);if(c&&c.length){b=c[0].P();for(let f=0,n=c.length;f<n;++f){const q=c[f];f+1===n?q.S(this.sa()):q.S(c[f+1].P())}}for(const f of this.ja(a))f.He(b);this.za&&this.Uc===a&&(this.za.disconnect(),this.za.connect(b))}sb(){return this.Tc}tb(){return this.ma}Yf(){this.Md=!0}ue(a,b){return b?this.v.pg(a).then(c=>{const f=this.f.createBuffer(1,c.length,48E3);f.getChannelData(0).set(c);return f}):new Promise((c,f)=>{this.f.decodeAudioData(a,
c,f)})}ua(a){this.v.ua(a)}Da(a){this.v.Da(a)}nd(a){let b=0;for(let c=0,f=this.D.length;c<f;++c){const n=this.D[c];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Ie(){let a=0;for(let b=0,c=this.ba.length;b<c;++b){const f=this.ba[b];this.ba[a]=f;f.ta()?f.c():++a}this.ba.length=a}*ja(a){if(a)for(const b of this.D)self.da.ve(b.$,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async zb(a,b,c,f,n){for(const q of this.ba)if(q.Sa()===b)return await P(q),q;if(n)return null;f&&(this.Xc||this.Md)&&
this.Ie();n="audio/webm; codecs=opus"===c&&!this.xg;f&&n&&this.Yf();a=!f||this.Xc||n?new self.qe(this,a,b,c,f,n):new self.oe(this,a,b,c,f);this.ba.push(a);await P(a);return a}async sc(a,b,c,f,n){for(const q of this.D)if(q.Sa()===b&&(q.$b()||n))return q.Ke(f),q;a=await this.zb(a,b,c,n);f="html5"===a.Ic?new self.pe(a.i,a,f):new self.re(a.i,a,f);this.D.push(f);return f}Oe(a){let b=this.lb.get(a);if(!b){let c=null;b={$c:0,promise:new Promise(f=>c=f),resolve:c};this.lb.set(a,b)}b.$c++}Rf(a){const b=this.lb.get(a);
if(!b)throw Error("expected pending tag");b.$c--;0===b.$c&&(b.resolve(),this.lb.delete(a))}pc(a){a||(a=this.Qd);return(a=this.lb.get(a))?a.promise:Promise.resolve()}Ab(){if(0<this.Ga.size)F(this);else for(const a of this.D)if(a.jd()){F(this);break}}Ea(){for(var a of this.Ga)a.Ea();a=this.dc();for(var b of this.D)b.Ea(a);b=this.D.filter(c=>c.jd()).map(c=>c.Ra());t(this,"state",{tickCount:this.Rd,audioInstances:b,analysers:[...this.Ga].map(c=>c.xe())});0===b.length&&0===this.Ga.size&&this.Nb&&(this.v.Sf(this.Zd),
this.Nb=!1)}lc(a,b,c){t(this,"trigger",{type:a,tag:b,aiid:c})}async Nf(a){const b=a.originalUrl,c=a.url,f=a.type,n=a.isMusic,q=a.tag,u=a.isLooping,x=a.vol,A=a.pos,w=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Qd=q;this.Oe(q);try{this.ga=await this.sc(b,c,f,q,n),w?(this.ga.wb(!0),this.ga.Je(w.x,w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&
this.ga.Le(w.uid)):this.ga.wb(!1),this.ga.Play(u,x,A,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Rf(q)}F(this)}jg(a){a=a.tag;for(const b of this.ja(a))b.la()}kg(){for(const a of this.D)a.la()}cg(a){const b=a.tag;a=a.paused;for(const c of this.ja(b))a?c.Ta():c.vb();this.Ab()}hg(a){const b=a.tag;a=a.vol;for(const c of this.ja(b))c.yb(a)}async af(a){const b=a.tag,c=a.vol,f=a.duration;a=a.stopOnEnd;await this.pc(b);for(const n of this.ja(b))n.we(c,
f,a);this.Ab()}ag(a){this.Tc=a.vol;for(const b of this.D)b.Gb()}bg(a){const b=a.tag;a=a.isMuted;for(const c of this.ja(b))c.od(a)}eg(a){this.ma=a.isSilent;this.v.xb(this.ma);for(const b of this.D)b.Fb()}$f(a){const b=a.tag;a=a.isLooping;for(const c of this.ja(b))c.nc(a)}async dg(a){const b=a.tag;a=a.rate;await this.pc(b);for(const c of this.ja(b))c.qd(a)}async Uf(a){const b=a.tag;a=a.pos;await this.pc(b);for(const c of this.ja(b))c.mc(a)}async Of(a){const b=a.originalUrl,c=a.url,f=a.type;a=a.isMusic;
try{await this.sc(b,c,f,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async ng(a){if(a=await this.zb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}og(){for(const a of this.ba)a.c();this.ba.length=0}fg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.oc(a);a&&this.f.suspend&&this.f.suspend()}Jf(a){this.Yb=a.timeScale;this.Mc=a.gameTime;this.Rd=a.tickCount;if(0!==this.Zc)for(var b of this.D)b.Fa();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const f of this.D)f.fa===a&&f.pd(c.x,c.y,c.angle)}}async rd(a){var b=a.type;const c=a.tag;var f=a.params;if("filter"===b)f=new self.ie(this,...f);else if("delay"===b)f=new self.ge(this,...f);else if("convolution"===b){b=null;try{b=await this.zb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}f=new self.fe(this,b.aa,...f);f.Vf(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)f=new self.je(this,...f);else if("phaser"===b)f=new self.le(this,...f);else if("gain"===b)f=new self.ke(this,...f);else if("tremolo"===b)f=new self.ne(this,...f);else if("ringmod"===b)f=new self.me(this,...f);else if("distortion"===b)f=new self.he(this,...f);else if("compressor"===b)f=new self.ee(this,...f);else if("analyser"===b)f=new self.de(this,...f);else throw Error("invalid effect type");this.ce(c,f);this.Cd()}Xf(a){const b=a.index,c=a.param,f=a.value,n=a.ramp,
q=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,f,n,q),this.Cd())}Qf(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const c of b)c.c();this.ca.delete(a);this.Dd(a)}}Ne(a){this.Ga.add(a);this.Ab()}Pf(a){this.Ga.delete(a)}Cd(){this.Qc||(this.Qc=!0,Promise.resolve().then(()=>this.Ze()))}Ze(){const a={};for(const [b,c]of this.ca)a[b]=c.map(f=>f.Ra());t(this,"fxstate",{fxstate:a});this.Qc=!1}async xf(a){const b=a.saveLoadMode;if(3!==b)for(var c of this.D)c.ta()&&1===
b||(c.ta()||2!==b)&&c.la();for(const f of this.ca.values())for(const n of f)n.c();this.ca.clear();this.Yb=a.timeScale;this.Mc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.ma=a.isSilent;this.v.xb(this.ma);this.Tc=a.masterVolume;c=[];for(const f of Object.values(a.effects))c.push(Promise.all(f.map(n=>this.rd(n))));await Promise.all(c);await Promise.all(a.playing.map(f=>this.hf(f,b)));this.Ab()}async hf(a,b){if(3!==b){var c=a.bufferOriginalUrl,f=a.bufferUrl,n=a.bufferType,
q=a.isMusic,u=a.tag,x=a.isLooping,A=a.volume,w=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.sc(c,f,n,u,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.Fe(a.pan);b.Play(x,A,w,0);a.isPlaying||b.Ta();b.xc(a)}}}zf(a,b){this.za&&this.za.disconnect();this.Uc=b.toLowerCase();this.za=this.f.createMediaStreamSource(a);this.za.connect(this.hd(this.Uc))}tf(){this.Jb||(this.Jb=this.f.createMediaStreamDestination(),this.Kb.connect(this.Jb));return this.Jb.stream}static ve(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Me(a){return a*e}static te(a){return Math.pow(10,a/20)}static gd(a){return Math.max(Math.min(self.da.te(a),1),0)}static Ee(a){return Math.log(a)/Math.log(10)*20}static De(a){return self.da.Ee(Math.max(Math.min(a,1),0))}static zg(a,b){return 1-Math.exp(-b*a)}};self.ka.ra(self.da)}"use strict";function P(e){e.Pb||(e.Pb=e.wc());return e.Pb}
self.cd=class{constructor(e,a,b,c,f){this.i=e;this.vg=a;this.Aa=b;this.R=c;this.sg=f;this.Ic="";this.Pb=null}c(){this.Pb=this.i=null}wc(){}W(){return this.i.W()}fc(){return this.vg}Sa(){return this.Aa}ec(){return this.R}ta(){return this.sg}ea(){}};"use strict";
self.oe=class extends self.cd{constructor(e,a,b,c,f){super(e,a,b,c,f);this.Ic="html5";this.I=new Audio;this.I.crossOrigin="anonymous";this.I.autoplay=!1;this.I.preload="auto";this.fb=this.gb=null;this.I.addEventListener("canplaythrough",()=>!0);this.kb=this.W().createGain();this.ib=null;this.I.addEventListener("canplay",()=>{this.gb&&(this.gb(),this.fb=this.gb=null);!this.ib&&this.I&&(this.ib=this.W().createMediaElementSource(this.I),this.ib.connect(this.kb))});this.onended=null;this.I.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.I.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.Aa}' error: `,n);this.fb&&(this.fb(n),this.fb=this.gb=null)})}c(){this.i.nd(this);this.kb.disconnect();this.kb=null;this.ib.disconnect();this.ib=null;this.I&&!this.I.paused&&this.I.pause();this.I=this.onended=null;super.c()}wc(){return new Promise((e,a)=>{this.gb=e;this.fb=a;this.I.src=this.Aa})}O(){return this.I}ea(){return this.I.duration}};"use strict";
async function Q(e){if(e.xa)return e.xa;var a=e.i.v;if("cordova"===a.C&&a.Be(e.Aa)&&"file:"===location.protocol)e.xa=await a.ac(e.Aa);else{a=await fetch(e.Aa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);e.xa=await a.arrayBuffer()}}async function R(e){if(e.aa)return e.aa;e.aa=await e.i.ue(e.xa,e.ug);e.xa=null}
self.qe=class extends self.cd{constructor(e,a,b,c,f,n){super(e,a,b,c,f);this.Ic="webaudio";this.aa=this.xa=null;this.ug=!!n}c(){this.i.nd(this);this.aa=this.xa=null;super.c()}async wc(){try{await Q(this),await R(this)}catch(e){console.error(`[Construct 3] Failed to load audio '${this.Aa}': `,e)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let e=0;self.dd=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Hb=e++;this.M=this.W().createGain();this.M.connect(this.sa());this.A=null;this.cb=!1;this.G=!0;this.V=this.ia=this.F=!1;this.ob=1;this.Ha=!1;this.Z=1;a=this.i.Zc;this.Rc=1===a&&!this.ta()||2===a;this.$a=this.fa=-1;this.Yd=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.hd(this.$)}sb(){return this.i.sb()}rb(){return this.Rc?this.i.Mc:
performance.now()/1E3}fc(){return this.L.fc()}Sa(){return this.L.Sa()}ec(){return this.L.ec()}ta(){return this.L.ta()}Ke(a){this.$=a}T(){}$b(){}IsPlaying(){return!this.G&&!this.F&&!this.T()}jd(){return!this.G&&!this.T()}Ca(){}ea(){return this.L.ea()}Play(){}la(){}Ta(){}vb(){}yb(a){this.ob=a;this.M.gain.cancelScheduledValues(0);this.$a=-1;this.M.gain.value=this.hc()}we(a,b,c){if(!this.Ha){a*=this.sb();var f=this.M.gain;f.cancelScheduledValues(0);var n=this.i.dc();b=n+b;f.setValueAtTime(f.value,n);
f.linearRampToValueAtTime(a,b);this.ob=a;this.$a=b;this.Yd=c}}Gb(){this.yb(this.ob)}Ea(a){-1!==this.$a&&a>=this.$a&&(this.$a=-1,this.Yd&&this.la(),this.i.lc("fade-ended",this.$,this.Hb))}hc(){const a=this.ob*this.sb();return isFinite(a)?a:0}od(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Fb())}tb(){return this.i.tb()}Fb(){}nc(){}qd(a){this.Z!==a&&(this.Z=a,this.Fa())}Fa(){}mc(){}oc(){}wb(a){a=!!a;this.cb!==a&&((this.cb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Td,this.A.distanceModel=
this.i.Kd,this.A.refDistance=this.i.Ud,this.A.maxDistance=this.i.Sd,this.A.rolloffFactor=this.i.Wd),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.sa())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Je(a,b,c,f,n,q){this.cb&&(this.pd(a,b,c),a=self.da.Me,this.A.coneInnerAngle=a(f),this.A.coneOuterAngle=a(n),this.A.coneOuterGain=q)}pd(a,b,c){this.cb&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(c),Math.sin(c),0))}Le(a){this.fa=a}ic(){}He(a){const b=
this.A||this.M;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Hb,tag:this.$,duration:this.ea(),volume:this.ob,isPlaying:this.IsPlaying(),playbackTime:this.Ca(),playbackRate:this.Z,uid:this.fa,bufferOriginalUrl:this.fc(),bufferUrl:"",bufferType:this.ec(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.ic(),pan:this.ye()}}xc(a){this.qd(a.playbackRate);this.od(a.isMuted)}ye(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Fe(a){a?(this.wb(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.wb(!1)}}}"use strict";
self.pe=class extends self.dd{constructor(e,a,b){super(e,a,b);this.L.kb.connect(this.M);this.L.onended=()=>this.zc()}c(){this.la();this.L.kb.disconnect();super.c()}O(){return this.L.O()}zc(){this.G=!0;this.fa=-1;this.i.lc("ended",this.$,this.Hb)}T(){return this.O().ended}$b(){return this.G?!0:this.T()}Ca(e){let a=this.O().currentTime;e&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(e,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.yb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.L.Sa()}' to position '${b}': `,f)}this.i.ua(c);this.F=this.G=!1;this.V=e;this.Z=1}la(){const e=this.O();e.paused||e.pause();this.i.Da(e);this.G=!0;this.F=!1;this.fa=-1}Ta(){if(!(this.F||this.G||this.T())){var e=this.O();e.paused||e.pause();this.i.Da(e);this.F=!0}}vb(){!this.F||this.G||this.T()||(this.i.ua(this.O()),this.F=!1)}Fb(){this.O().muted=this.Ha||this.tb()}nc(e){e=!!e;
this.V!==e&&(this.V=e,this.O().loop=e)}Fa(){let e=this.Z;this.Rc&&(e*=this.i.Yb);try{this.O().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}mc(e){if(!this.G&&!this.T())try{this.O().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,a)}}ic(){return this.Ca()}oc(e){e?this.IsPlaying()?(this.O().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.ua(this.O()),this.ia=!1)}};"use strict";
function S(e){e.j&&e.j.disconnect();e.j=null;e.Wa=null}
self.re=class extends self.dd{constructor(e,a,b){super(e,a,b);this.j=null;this.Sb=c=>this.zc(c);this.Nc=!0;this.Wa=null;this.N=this.Xb=0;this.Vc=1}c(){this.la();S(this);this.Sb=null;super.c()}zc(e){this.F||this.ia||e.target!==this.Wa||(this.G=this.Nc=!0,this.fa=-1,S(this),this.i.lc("ended",this.$,this.Hb))}T(){return!this.G&&this.j&&this.j.loop||this.F?!1:this.Nc}$b(){return!this.j||this.G?!0:this.T()}Ca(e){let a;a=this.F?this.N:this.rb()-this.Xb;e&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(e,
a,b,c){this.Vc=1;this.yb(a);S(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.aa;this.j.connect(this.M);this.Wa=this.j;this.j.onended=this.Sb;this.j.loop=e;this.j.start(c,b);this.F=this.G=this.Nc=!1;this.V=e;this.Z=1;this.Xb=this.rb()-b}la(){if(this.j)try{this.j.stop(0)}catch(e){}this.G=!0;this.F=!1;this.fa=-1}Ta(){this.F||this.G||this.T()||(this.N=this.Ca(!0),this.V&&(this.N%=this.ea()),this.F=!0,this.j.stop(0))}vb(){!this.F||this.G||this.T()||(S(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.aa,this.j.connect(this.M),this.Wa=this.j,this.j.onended=this.Sb,this.j.loop=this.V,this.Gb(),this.Fa(),this.Xb=this.rb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.F=!1)}hc(){return super.hc()*this.Vc}Fb(){this.Vc=this.Ha||this.tb()?0:1;this.Gb()}nc(e){e=!!e;this.V!==e&&(this.V=e,this.j&&(this.j.loop=e))}Fa(){let e=this.Z;this.Rc&&(e*=this.i.Yb);this.j&&(this.j.playbackRate.value=e)}mc(e){this.G||this.T()||(this.F?this.N=e:(this.Ta(),this.N=e,this.vb()))}ic(){return this.N}oc(e){e?
this.IsPlaying()?(this.ia=!0,this.N=this.Ca(!0),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(S(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.aa,this.j.connect(this.M),this.Wa=this.j,this.j.onended=this.Sb,this.j.loop=this.V,this.Gb(),this.Fa(),this.Xb=this.rb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.ia=!1)}xc(e){super.xc(e);this.N=e.resumePosition}};"use strict";
{class e{constructor(a){this.i=a;this.f=a.W();this.Nd=-1;this.R=this.$="";this.g=null}c(){this.f=null}Zf(a){this.Nd=a}gg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var n=this.f.currentTime;f+=n;switch(c){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,f)}}}Ra(){return{type:this.R,tag:this.$,params:this.g}}}
self.ie=class extends e{constructor(a,b,c,f,n,q,u){super(a);this.R="filter";this.g=[b,c,f,n,q,u];this.l=this.o();this.b=this.o();this.b.gain.value=u;this.a=this.o();this.a.gain.value=1-u;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=f;this.u.Q.value=n;this.u.gain.vlaue=q;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,f)}}};self.ge=class extends e{constructor(a,b,c,f){super(a);this.R="delay";this.g=[b,c,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.hb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.Za=this.o();this.Za.gain.value=c;this.l.connect(this.hb);this.l.connect(this.a);this.hb.connect(this.b);this.hb.connect(this.U);this.U.connect(this.Za);this.Za.connect(this.hb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.hb.disconnect();this.U.disconnect();this.Za.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){const n=self.da.gd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 4:this.g[1]=n(b);this.m(this.Za.gain,n(b),c,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,f)}}};self.fe=class extends e{constructor(a,b,c,f){super(a);this.R="convolution";this.g=[c,f];this.Id=this.Hd="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.Ya=this.f.createConvolver();this.Ya.normalize=c;this.Ya.buffer=b;this.l.connect(this.Ya);this.l.connect(this.a);this.Ya.connect(this.b)}c(){this.l.disconnect();this.Ya.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}Vf(a,b){this.Hd=a;this.Id=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Hd;a.bufferUrl="";a.bufferType=this.Id;return a}};self.je=class extends e{constructor(a,b,c,f,n,q){super(a);this.R="flanger";this.g=[b,c,f,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.ab=this.o();this.ab.gain.value=n;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.H=this.o();this.H.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.ab);this.ab.connect(this.U);this.s.connect(this.H);this.H.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();this.ab.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 6:this.g[1]=b/1E3;this.m(this.H.gain,b/1E3,c,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,f);break;case 8:this.g[3]=b/100,this.m(this.ab.gain,b/100,c,f)}}};self.le=class extends e{constructor(a,b,c,f,n,q,u){super(a);this.R="phaser";this.g=[b,c,f,n,q,u];this.l=this.o();this.a=this.o();this.a.gain.value=1-u/2;this.b=this.o();this.b.gain.value=u/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=q;this.H=this.o();this.H.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.H);this.H.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.H.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,f);break;case 6:this.g[3]=b;this.m(this.H.gain,b,c,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,f)}}};self.ke=class extends e{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,f){const n=self.da.gd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),c,f)}}};self.ne=class extends e{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.H=this.o();this.H.gain.value=c/2;this.s.connect(this.H);this.H.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.H.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,c,f);this.m(this.H.gain.value,b/2,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.me=class extends e{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.nb=this.o();
this.nb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.nb.gain);this.s.start(0);this.l.connect(this.nb);this.l.connect(this.a);this.nb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.nb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,c,f);this.m(this.a.gain,1-b,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.he=class extends e{constructor(a,b,c,f,n,q){super(a);this.R="distortion";this.g=[b,c,f,n,q];this.l=this.o();this.Ub=this.o();this.Tb=this.o();this.Wf(f,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.Zb=this.f.createWaveShaper();this.Kc=new Float32Array(65536);this.cf(b,c);this.Zb.curve=this.Kc;this.l.connect(this.Ub);this.l.connect(this.a);this.Ub.connect(this.Zb);
this.Zb.connect(this.Tb);this.Tb.connect(this.b)}c(){this.l.disconnect();this.Ub.disconnect();this.Zb.disconnect();this.Tb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Wf(a,b){.01>a&&(a=.01);this.Ub.gain.value=a;this.Tb.gain.value=Math.pow(1/a,.6)*b}cf(a,b){for(let c=0;32768>c;++c){let f=c/32768;f=this.ig(f,a,b);this.Kc[32768+c]=f;this.Kc[32768-c-1]=-f}}ig(a,b,c){c=1.05*c*b-b;const f=0>a?-a:a;return(f<b?f:b+c*self.da.zg(f-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}};self.ee=class extends e{constructor(a,b,c,f,n,q){super(a);this.R="compressor";this.g=[b,c,f,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=f;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.de=class extends e{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Ld=new Float32Array(this.h.frequencyBinCount);this.Xd=new Uint8Array(b);this.Vd=this.Ka=0;this.i.Ne(this)}c(){this.i.Pf(this);this.h.disconnect();super.c()}Ea(){this.h.getFloatFrequencyData(this.Ld);this.h.getByteTimeDomainData(this.Xd);const a=this.h.fftSize;let b=this.Ka=0;for(var c=0;c<a;++c){let f=(this.Xd[c]-128)/128;0>f&&(f=-f);
this.Ka<f&&(this.Ka=f);b+=f*f}c=self.da.De;this.Ka=c(this.Ka);this.Vd=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}xe(){return{tag:this.$,index:this.Nd,peak:this.Ka,rms:this.Vd,binCount:this.h.frequencyBinCount,freqBins:this.Ld}}}}"use strict";function T(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>t(e,"sw-message",a.data))}
function U(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(e):screen.webkitLockOrientation?a=screen.webkitLockOrientation(e):screen.mozLockOrientation?a=screen.mozLockOrientation(e):screen.msLockOrientation&&(a=screen.msLockOrientation(e));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ka.ra(class extends self.Ba{constructor(e){super(e,"browser");this.C="";E(this,[["get-initial-state",a=>{this.C=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>T(this)],
["alert",a=>this.yc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Ec(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>U(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this.Lg||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],["request-fullscreen",
a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{t(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;t(this,"backbutton")})}yc(e){alert(e.message)}Ec(e){e=e.isFocus;if("nwjs"===this.C){const a="nwjs"===this.C?nw.Window.get():null;e?a.focus():a.blur()}else e?window.focus():window.blur()}});"use strict";self.ka.ra(class extends self.Ba{constructor(e){super(e,"mouse");D(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
async function V(e,a){a=a.type;let b=!0;0===a?b=await W():1===a&&(b=await X());t(e,"permission-result",{type:a,result:b})}async function W(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function X(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.ka.ra(class extends self.Ba{constructor(e){super(e,"touch");D(this,"request-permission",a=>V(this,a))}});